#if !defined(__IANA_IP_PROTO_H)
#define __IANA_IP_PROTO_H

#define IP_PROTO_HOPOPT		0
#define IP_PROTO_ICMP		1
#define IP_PROTO_IGMP		2
#define IP_PROTO_GGP		3
#define IP_PROTO_IP		4
#define IP_PROTO_ST		5
#define IP_PROTO_TCP		6
#define IP_PROTO_CBT		7
#define IP_PROTO_EGP		8
#define IP_PROTO_IGP		9
#define IP_PROTO_BBN_RCC_MON	10
#define IP_PROTO_NVP_II		11
#define IP_PROTO_PUP		12
#define IP_PROTO_ARGUS		13
#define IP_PROTO_EMCON		14
#define IP_PROTO_XNET		15
#define IP_PROTO_CHAOS		16
#define IP_PROTO_UDP		17
#define IP_PROTO_MUX		18
#define IP_PROTO_DCN_MEAS	19
#define IP_PROTO_HMP		20
#define IP_PROTO_PRM		21
#define IP_PROTO_XNS_IDP		22
#define IP_PROTO_TRUNK_1		23
#define IP_PROTO_TRUNK_2		24
#define IP_PROTO_LEAF_1		25
#define IP_PROTO_LEAF_2		26
#define IP_PROTO_RDP		27
#define IP_PROTO_IRTP		28
#define IP_PROTO_ISO_TP4		29
#define IP_PROTO_NETBLT		30
#define IP_PROTO_MFE_NSP		31
#define IP_PROTO_MERIT_INP	32
#define IP_PROTO_DCCP		33
#define IP_PROTO_3PC		34
#define IP_PROTO_IDPR		35
#define IP_PROTO_XTP		36
#define IP_PROTO_DDP		37
#define IP_PROTO_IDPR_CMTP	38
#define IP_PROTO_TP_PLUSPLUS		39
#define IP_PROTO_IL		40
#define IP_PROTO_IPv6		41
#define IP_PROTO_SDRP		42
#define IP_PROTO_IPv6_Route	43
#define IP_PROTO_IPv6_Frag	44
#define IP_PROTO_IDRP		45
#define IP_PROTO_RSVP		46
#define IP_PROTO_GRE		47
#define IP_PROTO_DSR		48
#define IP_PROTO_BNA		49
#define IP_PROTO_ESP		50
#define IP_PROTO_AH		51
#define IP_PROTO_I_NLSP		52
#define IP_PROTO_SWIPE		53
#define IP_PROTO_NARP		54
#define IP_PROTO_MOBILE		55
#define IP_PROTO_TLSP		56
#define IP_PROTO_SKIP		57
#define IP_PROTO_IPv6_ICMP	58
#define IP_PROTO_IPv6_NoNxt	59
#define IP_PROTO_IPv6_Opts	60
#define IP_PROTO_any_host_internal 61
#define IP_PROTO_CFTP		62
#define IP_PROTO_any_local_network 63
#define IP_PROTO_SAT_EXPAK	64
#define IP_PROTO_KRYPTOLAN	65
#define IP_PROTO_RVD		66
#define IP_PROTO_IPPC		67
#define IP_PROTO_any_distributed_FS 68
#define IP_PROTO_SAT_MON		69
#define IP_PROTO_VISA		70
#define IP_PROTO_IPCV		71
#define IP_PROTO_CPNX		72
#define IP_PROTO_CPHB		73
#define IP_PROTO_WSN		74
#define IP_PROTO_PVP		75
#define IP_PROTO_BR_SAT_MON	76
#define IP_PROTO_SUN_ND		77
#define IP_PROTO_WB_MON		78
#define IP_PROTO_WB_EXPAK	79
#define IP_PROTO_ISO_IP		80
#define IP_PROTO_VMTP		81
#define IP_PROTO_SECURE_VMTP	82
#define IP_PROTO_VINES		83
#define IP_PROTO_TTP		84
#define IP_PROTO_NSFNET_IGP	85
#define IP_PROTO_DGP		86
#define IP_PROTO_TCF		87
#define IP_PROTO_EIGRP		88
#define IP_PROTO_OSPFIGP		89
#define IP_PROTO_Sprite_RPC	90
#define IP_PROTO_LARP		91
#define IP_PROTO_MTP		92
#define IP_PROTO_AX_25		93
#define IP_PROTO_IPIP		94
#define IP_PROTO_MICP		95
#define IP_PROTO_SCC_SP		96
#define IP_PROTO_ETHERIP		97
#define IP_PROTO_ENCAP		98
#define IP_PROTO_any_private_encryption	99
#define IP_PROTO_GMTP		100
#define IP_PROTO_IFMP		101
#define IP_PROTO_PNNI		102
#define IP_PROTO_PIM		103
#define IP_PROTO_ARIS		104
#define IP_PROTO_SCPS		105
#define IP_PROTO_QNX		106
#define IP_PROTO_A_N		107
#define IP_PROTO_IPComp		108
#define IP_PROTO_SNP		109
#define IP_PROTO_Compaq_Peer	110
#define IP_PROTO_IPX_in_IP	111
#define IP_PROTO_VRRP		112
#define IP_PROTO_PGM		113
#define IP_PROTO_any_0_hop_proto	114
#define IP_PROTO_L2TP		115
#define IP_PROTO_DDX		116
#define IP_PROTO_IATP		117
#define IP_PROTO_STP		118
#define IP_PROTO_SRP		119
#define IP_PROTO_UTI		120
#define IP_PROTO_SMP		121
#define IP_PROTO_SM		122
#define IP_PROTO_PTP		123
#define IP_PROTO_ISIS_over_IPv4	124
#define IP_PROTO_FIRE		125
#define IP_PROTO_CRTP		126
#define IP_PROTO_CRUDP		127
#define IP_PROTO_SSCOPMCE	128
#define IP_PROTO_IPLT		129
#define IP_PROTO_SPS		130
#define IP_PROTO_PIPE		131
#define IP_PROTO_SCTP		132
#define IP_PROTO_FC		133
#define IP_PROTO_RSVP_E2E_IGNORE	134
#define IP_PROTO_Mobility_Header	135
#define IP_PROTO_UDPLite		136
#define IP_PROTO_MPLS_in_IP	137
#define IP_PROTO_manet		138
#define IP_PROTO_HIP		139
#define IP_PROTO_Shim6		140
#define IP_PROTO_WESP		141
/* some more omitted  */

#endif 
